name: intl_usage
description: A Dart package to analyze and validate internationalization (i18n) resources, ensuring consistency and completeness across different locales.
version: 1.2.0
repository: https://github.com/ChiangChu/intl_usage

environment:
  sdk: ^3.4.3

keywords:
  - internationalization
  - i18n
  - localization
  - l10n
  - translation
  - validation

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  equatable: ^2.0.7
  flat: ^0.5.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.0.0
